on:
  push:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

    steps:  
      - name: Clonar Codigo
        uses: actions/checkout@v4

      - run: |
          ls
          echo "Hello World"

      - name: Terraform init
        run: |
          terraform init
          terraform fmt
          terraform validate

      - name: Terrafom Plan
        run: |
          terraform plan -out tfplan

      - name: Terrafom Apply
        run: |
          terraform apply tfplan